### ISSUE TITLE
Failed to compile github.com/hajimehoshi/ebiten/examples/2048 with an odd error

### ISSUE THREAD

**Issue by hajimehoshi** [tinygo-org/tinygo#1304]
```
git clone https://github.com/hajimehoshi/ebiten
cd ebiten
docker pull tinygo/tinygo:latest
docker run --rm -v $(pwd):/src -w /src tinygo/tinygo:latest tinygo build -o wasm.wasm -target=wasm -tags=example ./examples/2048/
```

this failed with the error:

```
fragment covers entire variable
  call void @llvm.dbg.value(metadata %"github.com/hajimehoshi/ebiten/internal/affine.ColorM"* %clr.impl, metadata !81356, metadata !DIExpression(DW_OP_LLVM_fragment, 0, 32)), !dbg !81396
!81356 = !DILocalVariable(name: "clr", arg: 7, scope: !81346, file: !3099, line: 50, type: !3088)
error: verification error after IR construction
```

**Comment by aykevl** [comment]
Interesting bug. You should be able to work around it with `-no-debug`.

**Comment by hajimehoshi** [comment]
Thanks. I tried

```
docker run --rm -v $(pwd):/src -w /src tinygo/tinygo:latest tinygo build -o wasm.wasm -target=wasm -no-debug -tags=example ./examples/2048/
```

but nothing was dumped. I guess some strange things happened...

**Comment by aykevl** [comment]
In that case, I suspect the build was successful but somehow the file wasn't written to the right location (possibly a Docker thing). You could try a native version of TinyGo instead of Docker.

**Comment by sago35** [comment]
```
sago35@sago35-B450GT3  ~/dev/src/github.com/hajimehoshi/ebiten (master)
$ git rev-parse HEAD
20a01ed328f0ed3309c0cec85c8b8e6201a8eb8b

sago35@sago35-B450GT3  ~/dev/src/github.com/hajimehoshi/ebiten (master)
$ tinygo version
tinygo version 0.15.0-dev-946184b linux/amd64 (using go version go1.14.4 and LLVM version 10.0.1)

sago35@sago35-B450GT3  ~/dev/src/github.com/hajimehoshi/ebiten (master)
$ tinygo build -o wasm.wasm -target wasm -tags example ./examples/2048/
fragment covers entire variable
  call void @llvm.dbg.value(metadata %"github.com/hajimehoshi/ebiten/internal/affine.ColorM"* %clr.impl, metadata !80360, metadata !DIExpression(DW_OP_LLVM_fragment, 0, 32)), !dbg !80400
!80360 = !DILocalVariable(name: "clr", arg: 7, scope: !80350, file: !3092, line: 50, type: !3081)
error: verification error after IR construction

sago35@sago35-B450GT3  ~/dev/src/github.com/hajimehoshi/ebiten (master)
$ tinygo build -o wasm.wasm -target wasm -tags example -no-debug ./examples/2048/
# math/big
-: interp: branch on a non-constant

traceback:
-:
  br i1 %1, label %if.then, label %if.done
-:
  %7 = call { double, i32 } @math.normalize(double %f, i8* undef, i8* undef)
-:
  %0 = call { double, i32 } @math.frexp(double %x, i8* undef, i8* undef)
-:
  %44 = call { double, i32 } @math.Frexp(double %x, i8* undef, i8* undef)
-:
  %5 = call %"math/big.Float"* @"(*math/big.Float).SetFloat64"(%"math/big.Float"* %3, double %x, i8* undef, i8* undef)
-:
  %51 = call %"math/big.Float"* @"math/big.NewFloat"(double 3.000000e+00, i8* undef, i8* undef)
```

**Comment by hajimehoshi** [comment]
Any updates?

**Comment by FrankReh** [comment]
I ran into the same problem with code I was building yesterday. Here is the reduced problem, just one main.go file. A few comments indicating what could be removed or replaced to make the problem go away. As @aykevl pointed out, it only happens when not passing -no-debug.

So in my particular case, the problem boiled down to calling a method with a value receiver for a struct that is essentially just a pointer but with the nuance that it is declared with a function field too (that can be removed by the Go compiler because its part of a zero length array). Why would one do this? The Go/wasm code uses this technique to keep the Value type from being compared with the == operator.

``` go
/*
	$ tinygo build -o=wasm.wasm -no-debug
	$ tinygo build -o=wasm.wasm
	fragment covers entire variable
	  call void @llvm.dbg.value(metadata i32* %b.p, metadata !6226, metadata !DIExpression(DW_OP_LLVM_fragment, 0, 32)), !dbg !6227
	!6226 = !DILocalVariable(name: "b", arg: 1, scope: !6212, file: !6213, line: 19, type: !6216)
	error: verification error after IR construction
*/
package main

type bar struct {
	_ [0]func() // removing this makes it work
	p *int      // removing this makes it work

	//placeholder byte // adding this makes it work
}

func main() {
	a := bar{}
	_ = a

	// Compiling with -no-debug makes it work
	a.ValueRecvMethod() // removing this makes it work

	// Using this line instead makes it work
	// a.PtrRecvMethod()
}

func (b bar) ValueRecvMethod() {}
func (b *bar) PtrRecvMethod()  {}
```

**Comment by FrankReh** [comment]
I see the same behavior with LLVM-11. Is there a way to capture what is being passed to LLVM to be able to ask the LLVM team about this error message means, or is it clearly in the tinygo code?

**Comment by yourjelly** [comment]
Using go 1.15.6 and tinygo 0.16.0 I am still getting unsuccessful builds, but it does leave this in the log on its attempts.

```# vendor/golang.org/x/crypto/cryptobyte
/usr/local/go/src/vendor/golang.org/x/crypto/cryptobyte/asn1.go:14:2: could not import golang.org/x/crypto/cryptobyte/asn1 (package not imported: golang.org/x/crypto/cryptobyte/asn1)

**Comment by deadprogram** [comment]
I think that is https://github.com/tinygo-org/tinygo/issues/1518

**Comment by hajimehoshi** [comment]
Any updates?

**Comment by aykevl** [comment]
The "fragment covers entire variable" error is indeed a bug in TinyGo and is not related to #1518. I will have to look into it. It's a bug in how debug info for function parameters is generated.

Edit: ah but the error from @Xuereb is indeed #1518 and should now be fixed.

**Comment by hajimehoshi** [comment]
Sure, thank you for responding! I'll recheck this.

**Comment by hajimehoshi** [comment]
I retried the compiling.

```
$ docker run --rm -v $(pwd):/src -w /src tinygo/tinygo:latest tinygo build -o wasm.wasm -target=wasm -tags=example ./examples/2048/
go: downloading golang.org/x/image v0.0.0-20200927104501-e162460cd6b5
go: downloading golang.org/x/text v0.3.0
# path/filepath
/usr/local/go/src/path/filepath/path.go:434:31: cannot use fileInfo (variable of type os.FileInfo) as fs.FileInfo value in argument to walkFn: missing method ModTime
/usr/local/go/src/path/filepath/path.go:438:25: cannot use fileInfo (variable of type os.FileInfo) as fs.FileInfo value in argument to walk: missing method ModTime
/usr/local/go/src/path/filepath/path.go:465:37: cannot use info (variable of type os.FileInfo) as fs.FileInfo value in struct literal: missing method ModTime
/usr/local/go/src/path/filepath/path.go:501:20: cannot use info (variable of type os.FileInfo) as fs.FileInfo value in argument to walk: missing method ModTime
/usr/local/go/src/path/filepath/path.go:516:17: f.ReadDir undefined (type *os.File has no field or method ReadDir)
/usr/local/go/src/path/filepath/symlink.go:89:6: invalid operation: mismatched types os.FileMode and fs.FileMode
```

Does this mean some of the standard library don't work? Then I'll try to fix this by not depending on these libraries.

The first issue has been resolved anyway. Thank you very much!

**Comment by aykevl** [comment]
> Does this mean some of the standard library don't work?

Yes, exactly.

Note that the "fragment covers entire variable" bug isn't fixed yet (you're just seeing a different error now), I have fixed it in this PR: https://github.com/tinygo-org/tinygo/pull/1752

**Comment by aykevl** [comment]
The PR is merged, so the "fragment covers entire variable" assert will be fixed in the next release.

**Comment by hajimehoshi** [comment]
BTW, I could not find the dependency on `filepath/path` from Ebiten. Probably this is used in a third party library. Would it be possible to enable to use `filepath/path` with TinyGo? This is a very common library and is hard to remove all usages from all the dependencies.

**Comment by eihigh** [comment]
How about tinygo using Go1.15? `fs.FileMode` is included in `io/fs` that was introduced in Go1.16.

**Comment by aykevl** [comment]
> Would it be possible to enable to use `filepath/path` with TinyGo?

Probably, given enough time. Feel free to help by making the os package more complete :)

**Comment by fgsch** [comment]
fwiw, ` invalid operation: mismatched types os.FileMode and fs.FileMode` seems to be fixed in current dev.

**Comment by deadprogram** [comment]
This was released with v0.18 so now closing. Thank you!
