### ISSUE TITLE
todo: go on interface call

### ISSUE THREAD

**Issue by fgsch** [tinygo-org/tinygo#1961]
This was discussed on slack a while back, but for the record, the code below fails with `/usr/local/Cellar/go/1.16.5/libexec/src/net/http/transport.go:1587:5: todo: go on interface call`:

```go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	fmt.Println(http.Cookie{})
}
```

TinyGo version:

`tinygo version 0.19.0-dev-1913cb76 darwin/amd64 (using go version go1.16.5 and LLVM version 11.0.0)`

Invocation:

`tinygo build -target wasm -o main.wasm main.go`

**Comment by aykevl** [comment]
I looked into this before and I believe my conclusion was that it's easier to finish refactoring the reflect package first.

**Comment by esimov** [comment]
This error is still happening for me. Is there any resolution regarding this issue?

**Comment by aykevl** [comment]
I have implemented this, after refactoring how interfaces are type asserted and interface methods are called: https://github.com/tinygo-org/tinygo/pull/2202

**Comment by esimov** [comment]
Thank you. I've tried to install it again via Homebrew, but I'm afraid is not updated yet, because I'm still receiving the above error.

**Comment by aykevl** [comment]
It's only a PR yet, not yet merged into the development branch even. So no, it's not part of Homebrew yet.

**Comment by esimov** [comment]
All right, thanks.

**Comment by dgryski** [comment]
Support for "go on interfaces" as been merged and tinygo 0.21 was released with this fix.  Closing this bug.  Please re-open if you're still encountering problems.
